import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { SuiGrpcClient } from "@mysten/sui/grpc";
import { Transaction } from "@mysten/sui/transactions";
import { getFaucetHost, requestSuiFromFaucetV2 } from "@mysten/sui/faucet";

const root = path.resolve(import.meta.dirname, "..");
const envPath = path.join(root, ".env.local");
const deployedPath = path.join(root, "src/lib/sui/deployed.json");
const bytecodeDir = path.join(root, "move/intenses/build/intenses/bytecode_modules");

const network = process.env.SUI_NETWORK === "devnet" ? "devnet" : "testnet";

const client = new SuiGrpcClient({
  network,
  baseUrl:
    network === "devnet"
      ? "https://fullnode.devnet.sui.io:443"
      : "https://fullnode.testnet.sui.io:443",
});

function readEnv(): Record<string, string> {
  if (!existsSync(envPath)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match) out[match[1]] = match[2];
  }
  return out;
}

function writeEnv(values: Record<string, string>) {
  const lines = [
    "# Generated by npm run chain:setup. Testnet sponsor only — do not commit.",
    ...Object.entries(values).map(([key, value]) => `${key}=${value}`),
    "",
  ];
  writeFileSync(envPath, lines.join("\n"));
}

async function sleep(ms: number) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

async function suiBalance(owner: string) {
  const { balance } = await client.getBalance({ owner });
  return BigInt(balance.balance);
}

async function fund(address: string) {
  const current = await suiBalance(address);
  if (current > 300_000_000n) {
    console.log(`Sponsor already holds ${current} MIST`);
    return;
  }
  console.log(`Requesting ${network} faucet for ${address}`);
  await requestSuiFromFaucetV2({
    host: getFaucetHost(network),
    recipient: address,
  });
  for (let attempt = 0; attempt < 20; attempt += 1) {
    await sleep(3000);
    const now = await suiBalance(address);
    if (now > 0n) {
      console.log(`Faucet landed: ${now} MIST`);
      return;
    }
  }
  throw new Error(`${network} faucet did not fund the sponsor address.`);
}

function txFailure(error: unknown) {
  if (!error) return "Transaction failed";
  if (typeof error === "string") return error;
  return JSON.stringify(error);
}

async function main() {
  const existing = existsSync(deployedPath)
    ? (JSON.parse(readFileSync(deployedPath, "utf8")) as { packageId?: string })
    : {};
  if (existing.packageId) {
    console.log(`Package already recorded at ${existing.packageId}. Nothing to publish.`);
    return;
  }

  const env = readEnv();
  const keypair = env.SPONSOR_SECRET_KEY
    ? Ed25519Keypair.fromSecretKey(env.SPONSOR_SECRET_KEY)
    : new Ed25519Keypair();
  const address = keypair.toSuiAddress();
  console.log(`Sponsor address: ${address}`);
  if (!env.SPONSOR_SECRET_KEY) {
    writeEnv({ SPONSOR_SECRET_KEY: keypair.getSecretKey() });
    console.log("Wrote sponsor key to .env.local");
  }

  await fund(address);

  const modules = ["usdc.mv", "intent.mv", "market.mv", "learn.mv"].map((name) =>
    Array.from(readFileSync(path.join(bytecodeDir, name))),
  );
  const tx = new Transaction();
  tx.setSender(address);
  const upgradeCap = tx.publish({
    modules,
    dependencies: [
      "0x0000000000000000000000000000000000000000000000000000000000000001",
      "0x0000000000000000000000000000000000000000000000000000000000000002",
    ],
  });
  tx.transferObjects([upgradeCap], address);

  const result = await keypair.signAndExecuteTransaction({
    transaction: tx,
    client,
    include: { effects: true, objectTypes: true, events: true },
  });

  if (result.$kind !== "Transaction") {
    throw new Error(txFailure(result.FailedTransaction.status.error));
  }

  const settled = await client.getTransaction({
    digest: result.Transaction.digest,
    include: { effects: true, objectTypes: true, events: true },
  });
  if (settled.$kind !== "Transaction") {
    throw new Error(txFailure(settled.FailedTransaction.status.error));
  }

  const executed = settled.Transaction;
  const types = executed.objectTypes ?? {};
  const changed = executed.effects?.changedObjects ?? [];
  const packageObj = changed.find((item) => item.outputState === "PackageWrite");
  const created = changed.filter((item) => item.idOperation === "Created");
  const findType = (suffix: string) =>
    created.find((item) => (types[item.objectId] ?? "").includes(suffix))?.objectId ?? "";

  const packageId = packageObj?.objectId ?? "";
  if (!packageId) {
    console.log(JSON.stringify({ types, changed }, null, 2));
    throw new Error("Publish succeeded but no package id was found.");
  }

  const deployed = {
    network,
    packageId,
    mintHubId: findType("::usdc::MintHub"),
    badgeRegistryId: findType("::learn::Registry"),
    usdcType: `${packageId}::usdc::USDC`,
    upgradeCapId: findType("::package::UpgradeCap"),
    sponsorAddress: address,
    publishDigest: executed.digest,
  };

  writeFileSync(deployedPath, `${JSON.stringify(deployed, null, 2)}\n`);
  console.log(JSON.stringify(deployed, null, 2));
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
