import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { SuiGrpcClient } from "@mysten/sui/grpc";
import { Transaction } from "@mysten/sui/transactions";
import { getFaucetHost, requestSuiFromFaucetV2 } from "@mysten/sui/faucet";

const root = path.resolve(import.meta.dirname, "..");
const envPath = path.join(root, ".env.local");
const deployedPath = path.join(root, "src/lib/sui/deployed.json");
const merchantsPath = path.join(root, "src/lib/sui/merchants.json");
const secretsPath = path.join(root, "data/merchant-secrets.json");
const bytecodeDir = path.join(root, "move/pago/build/pago/bytecode_modules");

const network = process.env.SUI_NETWORK === "testnet" ? "testnet" : "devnet";

const client = new SuiGrpcClient({
  network,
  baseUrl: network === "devnet" ? "https://fullnode.devnet.sui.io:443" : "https://fullnode.testnet.sui.io:443",
});

const desks = [
  { id: "harbor", name: "Harbor Bindery", city: "Tokyo", service: "Binds a short-run booklet and posts a delivery reference.", ask: "2800", verified: true },
  { id: "kanda", name: "Kanda Desk", city: "Tokyo", service: "Prepares the filing and confirms delivery in writing.", ask: "3000", verified: true },
  { id: "night", name: "Night Window", city: "Tokyo", service: "Offers the same job, and is not on the verification registry.", ask: "2500", verified: false },
];

function readEnv(): Record<string, string> {
  if (!existsSync(envPath)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match) out[match[1]] = match[2];
  }
  return out;
}

function writeEnv(values: Record<string, string>) {
  const lines = [
    "# Generated by npm run chain:setup. Demo sponsor only — do not commit.",
    ...Object.entries(values).map(([key, value]) => `${key}=${value}`),
    "",
  ];
  writeFileSync(envPath, lines.join("\n"));
}

async function sleep(ms: number) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

async function suiBalance(owner: string) {
  const { balance } = await client.getBalance({ owner });
  return BigInt(balance.balance);
}

async function fund(address: string) {
  const current = await suiBalance(address);
  if (current > 300_000_000n) {
    console.log(`Sponsor already holds ${current} MIST`);
    return;
  }
  console.log(`Requesting ${network} faucet for ${address}`);
  await requestSuiFromFaucetV2({ host: getFaucetHost(network), recipient: address });
  for (let attempt = 0; attempt < 20; attempt += 1) {
    await sleep(3000);
    const now = await suiBalance(address);
    if (now > 0n) {
      console.log(`Faucet landed: ${now} MIST`);
      return;
    }
  }
  throw new Error(`${network} faucet did not fund the sponsor address.`);
}

function txFailure(error: unknown) {
  if (!error) return "Transaction failed";
  if (typeof error === "string") return error;
  return JSON.stringify(error);
}

async function execute(signer: Ed25519Keypair, tx: Transaction) {
  tx.setSender(signer.toSuiAddress());
  const result = await signer.signAndExecuteTransaction({
    transaction: tx,
    client,
    include: { effects: true },
  });
  if (result.$kind !== "Transaction") throw new Error(txFailure(result.FailedTransaction.status.error));
  if (!result.Transaction.status.success) throw new Error(txFailure(result.Transaction.status.error));
  return result.Transaction.digest;
}

async function main() {
  const existing = existsSync(deployedPath)
    ? (JSON.parse(readFileSync(deployedPath, "utf8")) as { packageId?: string; merchantRegistryId?: string })
    : {};
  if (existing.packageId && existing.merchantRegistryId && process.env.FORCE_PUBLISH !== "1") {
    console.log(`Package already recorded at ${existing.packageId}. Set FORCE_PUBLISH=1 to publish again.`);
    return;
  }

  const env = readEnv();
  const keypair = env.SPONSOR_SECRET_KEY ? Ed25519Keypair.fromSecretKey(env.SPONSOR_SECRET_KEY) : new Ed25519Keypair();
  const address = keypair.toSuiAddress();
  console.log(`Sponsor address: ${address}`);
  if (!env.SPONSOR_SECRET_KEY) {
    writeEnv({ SPONSOR_SECRET_KEY: keypair.getSecretKey() });
    console.log("Wrote sponsor key to .env.local");
  }

  await fund(address);

  const modules = ["usdc.mv", "merchant.mv", "obligation.mv"].map((name) => Array.from(readFileSync(path.join(bytecodeDir, name))));
  const tx = new Transaction();
  tx.setSender(address);
  const upgradeCap = tx.publish({
    modules,
    dependencies: [
      "0x0000000000000000000000000000000000000000000000000000000000000001",
      "0x0000000000000000000000000000000000000000000000000000000000000002",
    ],
  });
  tx.transferObjects([upgradeCap], address);

  const result = await keypair.signAndExecuteTransaction({
    transaction: tx,
    client,
    include: { effects: true, objectTypes: true },
  });
  if (result.$kind !== "Transaction") throw new Error(txFailure(result.FailedTransaction.status.error));

  let settled = await client.getTransaction({
    digest: result.Transaction.digest,
    include: { effects: true, objectTypes: true },
  });
  for (let attempt = 0; attempt < 12 && settled.$kind !== "Transaction"; attempt += 1) {
    await sleep(1500);
    settled = await client.getTransaction({
      digest: result.Transaction.digest,
      include: { effects: true, objectTypes: true },
    }).catch(() => settled);
  }
  if (settled.$kind !== "Transaction") throw new Error(txFailure(settled.FailedTransaction.status.error));

  const executed = settled.Transaction;
  const types = executed.objectTypes ?? {};
  const changed = executed.effects?.changedObjects ?? [];
  const packageObj = changed.find((item) => item.outputState === "PackageWrite");
  const created = changed.filter((item) => item.idOperation === "Created");
  const findType = (suffix: string) => created.find((item) => (types[item.objectId] ?? "").includes(suffix))?.objectId ?? "";
  const packageId = packageObj?.objectId ?? "";
  if (!packageId) {
    console.log(JSON.stringify({ types, changed }, null, 2));
    throw new Error("Publish succeeded but no package id was found.");
  }

  const merchantRegistryId = findType("::merchant::Registry");
  const deployed = {
    network,
    packageId,
    mintHubId: findType("::usdc::MintHub"),
    merchantRegistryId,
    usdcType: `${packageId}::usdc::USDC`,
    upgradeCapId: findType("::package::UpgradeCap"),
    sponsorAddress: address,
    publishDigest: executed.digest,
  };
  if (!deployed.mintHubId || !merchantRegistryId) {
    console.log(JSON.stringify({ types, created }, null, 2));
    throw new Error("Publish succeeded but the mint hub or merchant registry was not found.");
  }

  const secrets: Record<string, string> = {};
  const addresses: Record<string, string> = {};
  for (const desk of desks) {
    const key = new Ed25519Keypair();
    secrets[desk.id] = key.getSecretKey();
    addresses[desk.id] = key.toSuiAddress();
    if (desk.verified) {
      const verify = new Transaction();
      verify.moveCall({
        target: `${packageId}::merchant::verify`,
        arguments: [verify.object(merchantRegistryId), verify.pure.address(key.toSuiAddress()), verify.pure.string(desk.name)],
      });
      const digest = await execute(keypair, verify);
      console.log(`Verified ${desk.name} in ${digest}`);
    }
  }

  mkdirSync(path.dirname(secretsPath), { recursive: true });
  writeFileSync(deployedPath, `${JSON.stringify(deployed, null, 2)}\n`);
  writeFileSync(merchantsPath, `${JSON.stringify(addresses, null, 2)}\n`);
  writeFileSync(secretsPath, `${JSON.stringify(secrets, null, 2)}\n`);
  console.log(JSON.stringify({ ...deployed, merchants: addresses }, null, 2));
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
